import { useRef, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { generateCopy } from "@/lib/copy.functions";
import { mockCopy, mockCtas, mockHomepage, mockServices } from "@/lib/mock-copy";
import {
  BUSINESS_TYPES, EMPTY_INPUT, EXAMPLE_INPUT, GOALS, TONES, sectionToText,
  type BusinessInput, type GeneratedCopy, type Section,
} from "@/lib/copy-types";
import { ActionPill, ResultSection } from "./ResultSection";

const FIELDS: { key: keyof BusinessInput; label: string }[] = [
  { key: "businessName", label: "Business name" },
  { key: "businessType", label: "Business type" },
  { key: "location", label: "Location" },
  { key: "targetCustomers", label: "Target customers" },
  { key: "services", label: "Main services" },
  { key: "usp", label: "Unique selling point" },
];

const SECTION_TITLES: Record<Section, string> = { homepage: "Homepage Copy", services: "Services", ctas: "CTA Sections" };

async function copyText(text: string, what: string) {
  try {
    await navigator.clipboard.writeText(text);
    toast.success(`${what} copied to clipboard`);
  } catch {
    toast.error("Couldn't copy — please select and copy manually");
  }
}

export function CopyGenerator() {
  const generate = useServerFn(generateCopy);
  const [input, setInput] = useState<BusinessInput>(EMPTY_INPUT);
  const [errors, setErrors] = useState<Partial<Record<keyof BusinessInput, string>>>({});
  const [copy, setCopy] = useState<GeneratedCopy | null>(null);
  const [loading, setLoading] = useState<Record<Section, boolean>>({ homepage: false, services: false, ctas: false });
  const [overrides, setOverrides] = useState<Record<Section, string | null>>({ homepage: null, services: null, ctas: null });
  const [source, setSource] = useState<"ai" | "demo" | null>(null);
  const seed = useRef(0);
  const resultsRef = useRef<HTMLDivElement>(null);
  const anyLoading = loading.homepage || loading.services || loading.ctas;

  const set = (k: keyof BusinessInput, v: string) => {
    setInput((p) => ({ ...p, [k]: v }));
    if (errors[k]) setErrors((e) => ({ ...e, [k]: undefined }));
  };

  const validate = (i: BusinessInput) => {
    const e: typeof errors = {};
    for (const f of FIELDS) if (!i[f.key].trim()) e[f.key] = `Please enter your ${f.label.toLowerCase()}.`;
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const run = async (i: BusinessInput, section?: Section) => {
    const sections: Section[] = section ? [section] : ["homepage", "services", "ctas"];
    setLoading((l) => ({ ...l, ...Object.fromEntries(sections.map((s) => [s, true])) }));
    seed.current += 1;
    let result: Partial<GeneratedCopy> | null = null;
    try {
      const r = await generate({ data: { input: i, section } });
      if (r.ok) { result = r.data; setSource("ai"); }
      else if (r.error === "rate_limited") toast.error("Too many requests right now — showing demo copy instead.");
      else if (r.error === "credits") toast.error("AI credits are used up — showing demo copy instead.");
    } catch { /* fall through to demo */ }
    if (!result) {
      setSource("demo");
      const s = seed.current;
      result = section === "homepage" ? { homepage: mockHomepage(i, s) }
        : section === "services" ? { services: mockServices(i, s) }
        : section === "ctas" ? { ctas: mockCtas(i, s) }
        : mockCopy(i, s);
    }
    setCopy((prev) => ({ ...(prev ?? mockCopy(i)), ...result } as GeneratedCopy));
    setOverrides((o) => ({ ...o, ...Object.fromEntries(sections.map((s) => [s, null])) }));
    setLoading({ homepage: false, services: false, ctas: false });
  };

  const onSubmit = (e?: React.FormEvent) => {
    e?.preventDefault();
    if (!validate(input)) { toast.error("Please fill in the highlighted fields."); return; }
    if (!copy) setCopy(mockCopy(input));
    setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 50);
    void run(input);
  };

  const tryExample = () => {
    setInput(EXAMPLE_INPUT);
    setErrors({});
    setCopy(mockCopy(EXAMPLE_INPUT));
    setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 50);
    void run(EXAMPLE_INPUT);
  };

  const textFor = (s: Section) => (copy ? overrides[s] ?? sectionToText(copy, s) : "");
  const allText = () => copy ? (["homepage", "services", "ctas"] as Section[]).map((s) => `===== ${SECTION_TITLES[s].toUpperCase()} =====\n\n${textFor(s)}`).join("\n\n\n") : "";

  const download = () => {
    const blob = new Blob([`${input.businessName} — Website Copy\nGenerated by LocalBiz AI\n\n${allText()}`], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${input.businessName.replace(/\W+/g, "-").toLowerCase() || "website"}-copy.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div className="grid gap-8 lg:grid-cols-12">
      {/* Form */}
      <div className="lg:col-span-5">
        <form onSubmit={onSubmit} noValidate className="rounded-2xl bg-background p-6 ring-1 ring-border sm:p-7 lg:sticky lg:top-24">
          <div className="mb-6 flex items-center justify-between gap-3">
            <h2 className="font-display text-xl font-semibold tracking-tight">Tell us about your business</h2>
            <button type="button" onClick={tryExample} disabled={anyLoading} className="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-accent/10 py-1.5 pl-2.5 pr-3 text-xs font-medium text-accent transition-colors hover:bg-accent/15 disabled:opacity-50">
              <span className="dot bg-accent" /> Try Example
            </button>
          </div>

          <div className="space-y-4">
            <Field label="Business name" error={errors.businessName}>
              <input className="field" aria-invalid={!!errors.businessName} value={input.businessName} onChange={(e) => set("businessName", e.target.value)} placeholder="e.g. Glow Studio" maxLength={120} />
            </Field>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field label="Business type" error={errors.businessType}>
                <select className="field" aria-invalid={!!errors.businessType} value={input.businessType} onChange={(e) => set("businessType", e.target.value)}>
                  <option value="">Select type</option>
                  {BUSINESS_TYPES.map((t) => <option key={t}>{t}</option>)}
                </select>
              </Field>
              <Field label="Location" error={errors.location}>
                <input className="field" aria-invalid={!!errors.location} value={input.location} onChange={(e) => set("location", e.target.value)} placeholder="e.g. Bengaluru" maxLength={120} />
              </Field>
            </div>
            <Field label="Target customers" error={errors.targetCustomers}>
              <input className="field" aria-invalid={!!errors.targetCustomers} value={input.targetCustomers} onChange={(e) => set("targetCustomers", e.target.value)} placeholder="Who do you serve?" maxLength={300} />
            </Field>
            <Field label="Main services" error={errors.services} hint="Separate with commas">
              <textarea rows={3} className="field" aria-invalid={!!errors.services} value={input.services} onChange={(e) => set("services", e.target.value)} placeholder="Haircuts, Hair coloring, Hair spa" maxLength={1500} />
            </Field>
            <Field label="Unique selling point" error={errors.usp}>
              <textarea rows={2} className="field" aria-invalid={!!errors.usp} value={input.usp} onChange={(e) => set("usp", e.target.value)} placeholder="What makes you different?" maxLength={600} />
            </Field>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field label="Brand tone">
                <select className="field" value={input.tone} onChange={(e) => set("tone", e.target.value)}>{TONES.map((t) => <option key={t}>{t}</option>)}</select>
              </Field>
              <Field label="Primary goal">
                <select className="field" value={input.goal} onChange={(e) => set("goal", e.target.value)}>{GOALS.map((t) => <option key={t}>{t}</option>)}</select>
              </Field>
            </div>
          </div>

          <button type="submit" disabled={anyLoading} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary py-3 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-deep disabled:opacity-60">
            {anyLoading ? "Generating…" : "Generate Website Copy"}
            <span className={`dot bg-primary-foreground/80 ${anyLoading ? "skel" : ""}`} />
          </button>
        </form>
      </div>

      {/* Results */}
      <div className="lg:col-span-7" ref={resultsRef} style={{ scrollMarginTop: 90 }}>
        <div className="rounded-2xl bg-card p-6 ring-1 ring-foreground/5 sm:p-8">
          <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <span className="dot bg-primary" />
              <h2 className="font-display text-xl font-semibold tracking-tight">Your generated copy</h2>
            </div>
            {source && !anyLoading && (
              <span className="text-[11px] font-medium text-muted-foreground">{source === "ai" ? "Written by AI" : "Demo mode"}</span>
            )}
          </div>

          {!copy ? (
            <div className="rounded-xl bg-background p-8 text-center ring-1 ring-border">
              <p className="font-display text-lg">Your website copy will appear here.</p>
              <p className="mt-2 text-sm text-muted-foreground">Fill in the form, or click <span className="font-medium text-accent">Try Example</span> to see it in action.</p>
            </div>
          ) : (
            <>
              <div className="mb-8 flex flex-wrap gap-2">
                <ActionPill label="Generate Again" onClick={() => onSubmit()} disabled={anyLoading} />
                <ActionPill label="Copy All Content" onClick={() => copyText(allText(), "All content")} disabled={anyLoading} />
                <ActionPill label="Download Copy" onClick={download} disabled={anyLoading} />
              </div>

              {(["homepage", "services", "ctas"] as Section[]).map((s, idx) => (
                <div key={s}>
                  {idx > 0 && <div className="my-8 h-px bg-border" />}
                  <ResultSection
                    title={SECTION_TITLES[s]}
                    loading={loading[s]}
                    plainText={sectionToText(copy, s)}
                    override={overrides[s]}
                    onCopy={() => copyText(textFor(s), SECTION_TITLES[s])}
                    onRegenerate={() => run(input, s)}
                    onSaveEdit={(t) => setOverrides((o) => ({ ...o, [s]: t }))}
                  >
                    {s === "homepage" && <HomepageView copy={copy} />}
                    {s === "services" && <ServicesView copy={copy} />}
                    {s === "ctas" && <CtasView copy={copy} />}
                  </ResultSection>
                </div>
              ))}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function Field({ label, error, hint, children }: { label: string; error?: string | undefined; hint?: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="label-cap">{label}{hint && <span className="ml-1 normal-case tracking-normal text-muted-foreground/70">· {hint}</span>}</span>
      {children}
      {error && <span className="mt-1 block text-xs text-destructive">{error}</span>}
    </label>
  );
}

function Mini({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="mb-1.5 text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">{label}</p>
      {children}
    </div>
  );
}

function HomepageView({ copy }: { copy: GeneratedCopy }) {
  const h = copy.homepage;
  return (
    <div className="space-y-6">
      <div className="rounded-xl bg-background p-5 ring-1 ring-border">
        <Mini label="Hero headline"><p className="font-display text-2xl leading-snug tracking-tight text-balance">{h.headline}</p></Mini>
        <p className="mt-3 text-[15px] leading-relaxed text-muted-foreground text-pretty">{h.subheadline}</p>
      </div>
      <Mini label="Value proposition"><p className="text-[15px] leading-relaxed">{h.valueProposition}</p></Mini>
      <Mini label="Business introduction"><p className="text-[15px] leading-relaxed">{h.intro}</p></Mini>
      <Mini label="Key benefits">
        <div className="grid gap-3 sm:grid-cols-3">
          {h.benefits.map((b) => (
            <div key={b.title} className="rounded-xl bg-background p-4 ring-1 ring-border">
              <p className="mb-1 text-sm font-semibold tracking-tight">{b.title}</p>
              <p className="text-sm leading-relaxed text-muted-foreground">{b.description}</p>
            </div>
          ))}
        </div>
      </Mini>
      <Mini label="Trust section">
        <p className="mb-2 font-display text-lg">{h.trust.heading}</p>
        <ul className="space-y-1.5">
          {h.trust.points.map((p) => <li key={p} className="flex items-start gap-2 text-sm"><span className="dot mt-1.5 bg-primary" />{p}</li>)}
        </ul>
      </Mini>
    </div>
  );
}

function ServicesView({ copy }: { copy: GeneratedCopy }) {
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      {copy.services.map((s) => (
        <div key={s.name} className="rounded-xl bg-background p-4 ring-1 ring-border">
          <p className="mb-1 font-display text-base font-semibold tracking-tight">{s.name}</p>
          <p className="text-sm leading-relaxed text-muted-foreground">{s.description}</p>
          <p className="mt-3 border-t border-border pt-3 text-sm leading-relaxed"><span className="font-medium text-primary">Benefit: </span>{s.benefit}</p>
        </div>
      ))}
    </div>
  );
}

function CtasView({ copy }: { copy: GeneratedCopy }) {
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      {copy.ctas.map((c, i) => (
        <div key={i} className="flex flex-col rounded-xl bg-background p-4 ring-1 ring-border">
          <p className="mb-2 text-[11px] font-medium uppercase tracking-[0.14em] text-accent">{c.purpose}</p>
          <p className="font-display text-lg leading-snug">{c.heading}</p>
          <p className="mt-1 flex-1 text-sm leading-relaxed text-muted-foreground">{c.supporting}</p>
          <span className="mt-4 inline-flex w-fit rounded-full bg-primary px-4 py-2 text-xs font-medium text-primary-foreground">{c.button}</span>
        </div>
      ))}
    </div>
  );
}
